#	$NetBSD$

# Common makefile for riscv architecture include files

INCS=	ansi.h asm.h bswap.h byte_swap.h cdefs.h \
	elf_machdep.h endian.h endian_machdep.h \
	float.h frame.h \
	int_const.h int_fmtio.h int_limits.h int_mwgwtypes.h int_types.h \
	limits.h \
	param.h \
	reg.h \
	setjmp.h signal.h \
	types.h wchar_limits.h

.include <bsd.kinc.mk>
