# Install RISC-V 64 architecture headers

.include <bsd.own.mk>

INCSDIR= /usr/include/riscv64

INCS= \
	archconst.h \
	archtypes.h \
	elf.h \
	fpu.h \
	interrupt.h \
	ipcconst.h \
	memory.h \
	stackframe.h \
	vm.h

.include <bsd.files.mk>
