# Install RISC-V 64 architecture headers

INCSDIR= /usr/include/riscv64

INCS=	archconst.h archtypes.h elf.h fpu.h interrupt.h \
	ipcconst.h memory.h partition.h stackframe.h vm.h

.include <bsd.kinc.mk>
