# Install RISC-V 64 architecture headers

INCSDIR= /usr/include/riscv64

INCS=	archconst.h archtypes.h cpu.h elf.h fpu.h interrupt.h \
	ipcconst.h memory.h partition.h stackframe.h vm.h

INCSYMLINKS+= \
	../riscv64/archconst.h /usr/include/evbriscv64/archconst.h \
	../riscv64/archtypes.h /usr/include/evbriscv64/archtypes.h \
	../riscv64/cpu.h /usr/include/evbriscv64/cpu.h \
	../riscv64/elf.h /usr/include/evbriscv64/elf.h \
	../riscv64/fpu.h /usr/include/evbriscv64/fpu.h \
	../riscv64/interrupt.h /usr/include/evbriscv64/interrupt.h \
	../riscv64/ipcconst.h /usr/include/evbriscv64/ipcconst.h \
	../riscv64/memory.h /usr/include/evbriscv64/memory.h \
	../riscv64/partition.h /usr/include/evbriscv64/partition.h \
	../riscv64/stackframe.h /usr/include/evbriscv64/stackframe.h \
	../riscv64/vm.h /usr/include/evbriscv64/vm.h

.include <bsd.kinc.mk>
