# RISC-V 64-bit architecture-specific tests
#
# RISC-V tests are located in ../../riscv64/ and have their own test framework
# with run_tests.sh. No architecture-specific tests need to be added to the
# main test framework at this time.