#	$NetBSD$

INCSDIR= /usr/include/evbriscv64

# evbriscv64 inherits from riscv
.PATH: ${.CURDIR}/../../riscv/include

INCS=	ansi.h asm.h bswap.h byte_swap.h cdefs.h \
	elf_machdep.h endian.h endian_machdep.h \
	float.h frame.h \
	int_const.h int_fmtio.h int_limits.h int_mwgwtypes.h int_types.h \
	limits.h \
	mcontext.h \
	mutex.h \
	multiboot.h \
	param.h \
	profile.h \
	reg.h \
	rwlock.h \
	setjmp.h signal.h \
	types.h vmparam.h wchar_limits.h

.include <bsd.kinc.mk>
