#	$NetBSD$

INCSDIR= /usr/include/evbriscv64

# evbriscv64 inherits from riscv
.PATH: ${.CURDIR}/../../riscv/include

INCS=	aout_machdep.h ansi.h asm.h bswap.h byte_swap.h cdefs.h \
	cpu.h \
	disklabel.h \
	elf_machdep.h endian.h endian_machdep.h \
	fenv.h float.h frame.h \
	ieee.h ieeefp.h \
	int_const.h int_fmtio.h int_limits.h int_mwgwtypes.h int_types.h \
	kcore.h limits.h lock.h math.h \
	mcontext.h \
	mutex.h \
	multiboot.h \
	param.h \
	pcb.h \
	proc.h \
	profile.h \
	reg.h \
	rwlock.h \
	setjmp.h signal.h \
	sysreg.h \
	types.h vmparam.h wchar_limits.h

.include <bsd.kinc.mk>
